'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { CotButton as CotButtonElement, defineCustomElement as defineCotButton } from "@mng/stencil-components/dist/components/cot-button.js";
import { CotTextbox as CotTextboxElement, defineCustomElement as defineCotTextbox } from "@mng/stencil-components/dist/components/cot-textbox.js";
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "@mng/stencil-components/dist/components/my-component.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type CotButtonEvents = NonNullable<unknown>;

export const CotButton: StencilReactComponent<CotButtonElement, CotButtonEvents> = /*@__PURE__*/ createComponent<CotButtonElement, CotButtonEvents>({
    tagName: 'cot-button',
    elementClass: CotButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CotButtonEvents,
    defineCustomElement: defineCotButton
});

export type CotTextboxEvents = NonNullable<unknown>;

export const CotTextbox: StencilReactComponent<CotTextboxElement, CotTextboxEvents> = /*@__PURE__*/ createComponent<CotTextboxElement, CotTextboxEvents>({
    tagName: 'cot-textbox',
    elementClass: CotTextboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CotTextboxEvents,
    defineCustomElement: defineCotTextbox
});

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});
